# Generated by Django 4.2.7 on 2023-11-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
