# Generated by Django 4.2.7 on 2023-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do", "0002_alter_todo_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
