# Generated by Django 4.2.7 on 2023-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do", "0003_alter_todo_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
